//go:build !ignore_autogenerated

/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CoreRef) DeepCopyInto(out *CoreRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CoreRef.
func (in *CoreRef) DeepCopy() *CoreRef {
	if in == nil {
		return nil
	}
	out := new(CoreRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DHCPGuarding) DeepCopyInto(out *DHCPGuarding) {
	*out = *in
	if in.TrustedDHCPServerIPAddresses != nil {
		in, out := &in.TrustedDHCPServerIPAddresses, &out.TrustedDHCPServerIPAddresses
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DHCPGuarding.
func (in *DHCPGuarding) DeepCopy() *DHCPGuarding {
	if in == nil {
		return nil
	}
	out := new(DHCPGuarding)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeviceTagSelector) DeepCopyInto(out *DeviceTagSelector) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeviceTagSelector.
func (in *DeviceTagSelector) DeepCopy() *DeviceTagSelector {
	if in == nil {
		return nil
	}
	out := new(DeviceTagSelector)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GatewayManagedIPv4Configuration) DeepCopyInto(out *GatewayManagedIPv4Configuration) {
	*out = *in
	if in.AdditionalHostIPSubnets != nil {
		in, out := &in.AdditionalHostIPSubnets, &out.AdditionalHostIPSubnets
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GatewayManagedIPv4Configuration.
func (in *GatewayManagedIPv4Configuration) DeepCopy() *GatewayManagedIPv4Configuration {
	if in == nil {
		return nil
	}
	out := new(GatewayManagedIPv4Configuration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GatewayNetworkOptions) DeepCopyInto(out *GatewayNetworkOptions) {
	*out = *in
	in.IPv4Configuration.DeepCopyInto(&out.IPv4Configuration)
	if in.IPv6Configuration != nil {
		in, out := &in.IPv6Configuration, &out.IPv6Configuration
		*out = new(IPv6Configuration)
		(*in).DeepCopyInto(*out)
	}
	if in.MDNSForwardingEnabled != nil {
		in, out := &in.MDNSForwardingEnabled, &out.MDNSForwardingEnabled
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GatewayNetworkOptions.
func (in *GatewayNetworkOptions) DeepCopy() *GatewayNetworkOptions {
	if in == nil {
		return nil
	}
	out := new(GatewayNetworkOptions)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IPv6ClientAddressAssignment) DeepCopyInto(out *IPv6ClientAddressAssignment) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IPv6ClientAddressAssignment.
func (in *IPv6ClientAddressAssignment) DeepCopy() *IPv6ClientAddressAssignment {
	if in == nil {
		return nil
	}
	out := new(IPv6ClientAddressAssignment)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IPv6Configuration) DeepCopyInto(out *IPv6Configuration) {
	*out = *in
	out.ClientAddressAssignment = in.ClientAddressAssignment
	if in.AdditionalHostIPSubnets != nil {
		in, out := &in.AdditionalHostIPSubnets, &out.AdditionalHostIPSubnets
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.DNSServerIPAddressesOverride != nil {
		in, out := &in.DNSServerIPAddressesOverride, &out.DNSServerIPAddressesOverride
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.RouterAdvertisement != nil {
		in, out := &in.RouterAdvertisement, &out.RouterAdvertisement
		*out = new(RouterAdvertisement)
		**out = **in
	}
	if in.PrefixDelegationWAN != nil {
		in, out := &in.PrefixDelegationWAN, &out.PrefixDelegationWAN
		*out = new(WANSelector)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IPv6Configuration.
func (in *IPv6Configuration) DeepCopy() *IPv6Configuration {
	if in == nil {
		return nil
	}
	out := new(IPv6Configuration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IotOptimizedWifiOptions) DeepCopyInto(out *IotOptimizedWifiOptions) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IotOptimizedWifiOptions.
func (in *IotOptimizedWifiOptions) DeepCopy() *IotOptimizedWifiOptions {
	if in == nil {
		return nil
	}
	out := new(IotOptimizedWifiOptions)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RouterAdvertisement) DeepCopyInto(out *RouterAdvertisement) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RouterAdvertisement.
func (in *RouterAdvertisement) DeepCopy() *RouterAdvertisement {
	if in == nil {
		return nil
	}
	out := new(RouterAdvertisement)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StandardWifiOptions) DeepCopyInto(out *StandardWifiOptions) {
	*out = *in
	if in.BroadcastingFrequenciesGHz != nil {
		in, out := &in.BroadcastingFrequenciesGHz, &out.BroadcastingFrequenciesGHz
		*out = make([]WifiBroadcastingFrequencyGHz, len(*in))
		copy(*out, *in)
	}
	if in.BandSteeringEnabled != nil {
		in, out := &in.BandSteeringEnabled, &out.BandSteeringEnabled
		*out = new(bool)
		**out = **in
	}
	if in.MloEnabled != nil {
		in, out := &in.MloEnabled, &out.MloEnabled
		*out = new(bool)
		**out = **in
	}
	if in.DNSAssistanceConfiguration != nil {
		in, out := &in.DNSAssistanceConfiguration, &out.DNSAssistanceConfiguration
		*out = new(WifiDNSAssistanceConfiguration)
		(*in).DeepCopyInto(*out)
	}
	if in.DtimPeriodByFrequencyGHzOverride != nil {
		in, out := &in.DtimPeriodByFrequencyGHzOverride, &out.DtimPeriodByFrequencyGHzOverride
		*out = new(WifiDtimPeriodConfiguration)
		**out = **in
	}
	if in.HandoffSuggestionsConfiguration != nil {
		in, out := &in.HandoffSuggestionsConfiguration, &out.HandoffSuggestionsConfiguration
		*out = new(WifiHandoffSuggestionsConfiguration)
		(*in).DeepCopyInto(*out)
	}
	if in.HotspotConfiguration != nil {
		in, out := &in.HotspotConfiguration, &out.HotspotConfiguration
		*out = new(WifiHotspotConfiguration)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StandardWifiOptions.
func (in *StandardWifiOptions) DeepCopy() *StandardWifiOptions {
	if in == nil {
		return nil
	}
	out := new(StandardWifiOptions)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SwitchManagedIPv4Configuration) DeepCopyInto(out *SwitchManagedIPv4Configuration) {
	*out = *in
	if in.AdditionalHostIPSubnets != nil {
		in, out := &in.AdditionalHostIPSubnets, &out.AdditionalHostIPSubnets
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SwitchManagedIPv4Configuration.
func (in *SwitchManagedIPv4Configuration) DeepCopy() *SwitchManagedIPv4Configuration {
	if in == nil {
		return nil
	}
	out := new(SwitchManagedIPv4Configuration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SwitchNetworkOptions) DeepCopyInto(out *SwitchNetworkOptions) {
	*out = *in
	in.IPv4Configuration.DeepCopyInto(&out.IPv4Configuration)
	out.DeviceTag = in.DeviceTag
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SwitchNetworkOptions.
func (in *SwitchNetworkOptions) DeepCopy() *SwitchNetworkOptions {
	if in == nil {
		return nil
	}
	out := new(SwitchNetworkOptions)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UnifiController) DeepCopyInto(out *UnifiController) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UnifiController.
func (in *UnifiController) DeepCopy() *UnifiController {
	if in == nil {
		return nil
	}
	out := new(UnifiController)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *UnifiController) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UnifiControllerList) DeepCopyInto(out *UnifiControllerList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]UnifiController, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UnifiControllerList.
func (in *UnifiControllerList) DeepCopy() *UnifiControllerList {
	if in == nil {
		return nil
	}
	out := new(UnifiControllerList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *UnifiControllerList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UnifiControllerSpec) DeepCopyInto(out *UnifiControllerSpec) {
	*out = *in
	if in.SecretRef != nil {
		in, out := &in.SecretRef, &out.SecretRef
		*out = new(v1.SecretKeySelector)
		(*in).DeepCopyInto(*out)
	}
	if in.InsecureSkipVerify != nil {
		in, out := &in.InsecureSkipVerify, &out.InsecureSkipVerify
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UnifiControllerSpec.
func (in *UnifiControllerSpec) DeepCopy() *UnifiControllerSpec {
	if in == nil {
		return nil
	}
	out := new(UnifiControllerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UnifiControllerStatus) DeepCopyInto(out *UnifiControllerStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UnifiControllerStatus.
func (in *UnifiControllerStatus) DeepCopy() *UnifiControllerStatus {
	if in == nil {
		return nil
	}
	out := new(UnifiControllerStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UnifiFirewallZone) DeepCopyInto(out *UnifiFirewallZone) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UnifiFirewallZone.
func (in *UnifiFirewallZone) DeepCopy() *UnifiFirewallZone {
	if in == nil {
		return nil
	}
	out := new(UnifiFirewallZone)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *UnifiFirewallZone) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UnifiFirewallZoneList) DeepCopyInto(out *UnifiFirewallZoneList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]UnifiFirewallZone, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UnifiFirewallZoneList.
func (in *UnifiFirewallZoneList) DeepCopy() *UnifiFirewallZoneList {
	if in == nil {
		return nil
	}
	out := new(UnifiFirewallZoneList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *UnifiFirewallZoneList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UnifiFirewallZoneSpec) DeepCopyInto(out *UnifiFirewallZoneSpec) {
	*out = *in
	out.SiteRef = in.SiteRef
	if in.NetworkRefs != nil {
		in, out := &in.NetworkRefs, &out.NetworkRefs
		*out = make([]CoreRef, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UnifiFirewallZoneSpec.
func (in *UnifiFirewallZoneSpec) DeepCopy() *UnifiFirewallZoneSpec {
	if in == nil {
		return nil
	}
	out := new(UnifiFirewallZoneSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UnifiFirewallZoneStatus) DeepCopyInto(out *UnifiFirewallZoneStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UnifiFirewallZoneStatus.
func (in *UnifiFirewallZoneStatus) DeepCopy() *UnifiFirewallZoneStatus {
	if in == nil {
		return nil
	}
	out := new(UnifiFirewallZoneStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UnifiNetwork) DeepCopyInto(out *UnifiNetwork) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UnifiNetwork.
func (in *UnifiNetwork) DeepCopy() *UnifiNetwork {
	if in == nil {
		return nil
	}
	out := new(UnifiNetwork)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *UnifiNetwork) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UnifiNetworkList) DeepCopyInto(out *UnifiNetworkList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]UnifiNetwork, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UnifiNetworkList.
func (in *UnifiNetworkList) DeepCopy() *UnifiNetworkList {
	if in == nil {
		return nil
	}
	out := new(UnifiNetworkList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *UnifiNetworkList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UnifiNetworkSpec) DeepCopyInto(out *UnifiNetworkSpec) {
	*out = *in
	out.SiteRef = in.SiteRef
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.DHCPGuarding != nil {
		in, out := &in.DHCPGuarding, &out.DHCPGuarding
		*out = new(DHCPGuarding)
		(*in).DeepCopyInto(*out)
	}
	if in.Gateway != nil {
		in, out := &in.Gateway, &out.Gateway
		*out = new(GatewayNetworkOptions)
		(*in).DeepCopyInto(*out)
	}
	if in.Switch != nil {
		in, out := &in.Switch, &out.Switch
		*out = new(SwitchNetworkOptions)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UnifiNetworkSpec.
func (in *UnifiNetworkSpec) DeepCopy() *UnifiNetworkSpec {
	if in == nil {
		return nil
	}
	out := new(UnifiNetworkSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UnifiNetworkStatus) DeepCopyInto(out *UnifiNetworkStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UnifiNetworkStatus.
func (in *UnifiNetworkStatus) DeepCopy() *UnifiNetworkStatus {
	if in == nil {
		return nil
	}
	out := new(UnifiNetworkStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UnifiSite) DeepCopyInto(out *UnifiSite) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UnifiSite.
func (in *UnifiSite) DeepCopy() *UnifiSite {
	if in == nil {
		return nil
	}
	out := new(UnifiSite)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *UnifiSite) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UnifiSiteList) DeepCopyInto(out *UnifiSiteList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]UnifiSite, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UnifiSiteList.
func (in *UnifiSiteList) DeepCopy() *UnifiSiteList {
	if in == nil {
		return nil
	}
	out := new(UnifiSiteList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *UnifiSiteList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UnifiSiteSpec) DeepCopyInto(out *UnifiSiteSpec) {
	*out = *in
	out.ControllerRef = in.ControllerRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UnifiSiteSpec.
func (in *UnifiSiteSpec) DeepCopy() *UnifiSiteSpec {
	if in == nil {
		return nil
	}
	out := new(UnifiSiteSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UnifiSiteStatus) DeepCopyInto(out *UnifiSiteStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UnifiSiteStatus.
func (in *UnifiSiteStatus) DeepCopy() *UnifiSiteStatus {
	if in == nil {
		return nil
	}
	out := new(UnifiSiteStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UnifiWifiBroadcast) DeepCopyInto(out *UnifiWifiBroadcast) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UnifiWifiBroadcast.
func (in *UnifiWifiBroadcast) DeepCopy() *UnifiWifiBroadcast {
	if in == nil {
		return nil
	}
	out := new(UnifiWifiBroadcast)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *UnifiWifiBroadcast) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UnifiWifiBroadcastList) DeepCopyInto(out *UnifiWifiBroadcastList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]UnifiWifiBroadcast, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UnifiWifiBroadcastList.
func (in *UnifiWifiBroadcastList) DeepCopy() *UnifiWifiBroadcastList {
	if in == nil {
		return nil
	}
	out := new(UnifiWifiBroadcastList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *UnifiWifiBroadcastList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UnifiWifiBroadcastSpec) DeepCopyInto(out *UnifiWifiBroadcastSpec) {
	*out = *in
	out.NetworkRef = in.NetworkRef
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.Channel2gLockedTo6 != nil {
		in, out := &in.Channel2gLockedTo6, &out.Channel2gLockedTo6
		*out = new(bool)
		**out = **in
	}
	if in.DtimPeriod2gLockedTo3 != nil {
		in, out := &in.DtimPeriod2gLockedTo3, &out.DtimPeriod2gLockedTo3
		*out = new(bool)
		**out = **in
	}
	in.SecurityConfiguration.DeepCopyInto(&out.SecurityConfiguration)
	if in.DeviceTags != nil {
		in, out := &in.DeviceTags, &out.DeviceTags
		*out = make([]DeviceTagSelector, len(*in))
		copy(*out, *in)
	}
	if in.BasicDataRateKbpsByFrequencyGHz != nil {
		in, out := &in.BasicDataRateKbpsByFrequencyGHz, &out.BasicDataRateKbpsByFrequencyGHz
		*out = new(WifiBasicDataRateConfiguration)
		**out = **in
	}
	if in.BlackoutScheduleConfiguration != nil {
		in, out := &in.BlackoutScheduleConfiguration, &out.BlackoutScheduleConfiguration
		*out = new(WifiBlackoutScheduleConfiguration)
		(*in).DeepCopyInto(*out)
	}
	if in.ClientFilteringPolicy != nil {
		in, out := &in.ClientFilteringPolicy, &out.ClientFilteringPolicy
		*out = new(WifiClientFilteringPolicy)
		(*in).DeepCopyInto(*out)
	}
	if in.MDNSProxyConfiguration != nil {
		in, out := &in.MDNSProxyConfiguration, &out.MDNSProxyConfiguration
		*out = new(WifiMDNSProxyConfiguration)
		(*in).DeepCopyInto(*out)
	}
	if in.MulticastFilteringPolicy != nil {
		in, out := &in.MulticastFilteringPolicy, &out.MulticastFilteringPolicy
		*out = new(WifiMulticastFilteringPolicy)
		(*in).DeepCopyInto(*out)
	}
	if in.Standard != nil {
		in, out := &in.Standard, &out.Standard
		*out = new(StandardWifiOptions)
		(*in).DeepCopyInto(*out)
	}
	if in.IotOptimized != nil {
		in, out := &in.IotOptimized, &out.IotOptimized
		*out = new(IotOptimizedWifiOptions)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UnifiWifiBroadcastSpec.
func (in *UnifiWifiBroadcastSpec) DeepCopy() *UnifiWifiBroadcastSpec {
	if in == nil {
		return nil
	}
	out := new(UnifiWifiBroadcastSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UnifiWifiBroadcastStatus) DeepCopyInto(out *UnifiWifiBroadcastStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UnifiWifiBroadcastStatus.
func (in *UnifiWifiBroadcastStatus) DeepCopy() *UnifiWifiBroadcastStatus {
	if in == nil {
		return nil
	}
	out := new(UnifiWifiBroadcastStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WANSelector) DeepCopyInto(out *WANSelector) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WANSelector.
func (in *WANSelector) DeepCopy() *WANSelector {
	if in == nil {
		return nil
	}
	out := new(WANSelector)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WifiBasicDataRateConfiguration) DeepCopyInto(out *WifiBasicDataRateConfiguration) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WifiBasicDataRateConfiguration.
func (in *WifiBasicDataRateConfiguration) DeepCopy() *WifiBasicDataRateConfiguration {
	if in == nil {
		return nil
	}
	out := new(WifiBasicDataRateConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WifiBlackoutScheduleConfiguration) DeepCopyInto(out *WifiBlackoutScheduleConfiguration) {
	*out = *in
	if in.Days != nil {
		in, out := &in.Days, &out.Days
		*out = make([]WifiBlackoutScheduleDay, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WifiBlackoutScheduleConfiguration.
func (in *WifiBlackoutScheduleConfiguration) DeepCopy() *WifiBlackoutScheduleConfiguration {
	if in == nil {
		return nil
	}
	out := new(WifiBlackoutScheduleConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WifiBlackoutScheduleDay) DeepCopyInto(out *WifiBlackoutScheduleDay) {
	*out = *in
	if in.TimeRanges != nil {
		in, out := &in.TimeRanges, &out.TimeRanges
		*out = make([]WifiBlackoutTimeRange, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WifiBlackoutScheduleDay.
func (in *WifiBlackoutScheduleDay) DeepCopy() *WifiBlackoutScheduleDay {
	if in == nil {
		return nil
	}
	out := new(WifiBlackoutScheduleDay)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WifiBlackoutTimeRange) DeepCopyInto(out *WifiBlackoutTimeRange) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WifiBlackoutTimeRange.
func (in *WifiBlackoutTimeRange) DeepCopy() *WifiBlackoutTimeRange {
	if in == nil {
		return nil
	}
	out := new(WifiBlackoutTimeRange)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WifiClientFilteringPolicy) DeepCopyInto(out *WifiClientFilteringPolicy) {
	*out = *in
	if in.MacAddressFilter != nil {
		in, out := &in.MacAddressFilter, &out.MacAddressFilter
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WifiClientFilteringPolicy.
func (in *WifiClientFilteringPolicy) DeepCopy() *WifiClientFilteringPolicy {
	if in == nil {
		return nil
	}
	out := new(WifiClientFilteringPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WifiDNSAssistanceConfiguration) DeepCopyInto(out *WifiDNSAssistanceConfiguration) {
	*out = *in
	if in.Servers != nil {
		in, out := &in.Servers, &out.Servers
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WifiDNSAssistanceConfiguration.
func (in *WifiDNSAssistanceConfiguration) DeepCopy() *WifiDNSAssistanceConfiguration {
	if in == nil {
		return nil
	}
	out := new(WifiDNSAssistanceConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WifiDtimPeriodConfiguration) DeepCopyInto(out *WifiDtimPeriodConfiguration) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WifiDtimPeriodConfiguration.
func (in *WifiDtimPeriodConfiguration) DeepCopy() *WifiDtimPeriodConfiguration {
	if in == nil {
		return nil
	}
	out := new(WifiDtimPeriodConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WifiEnterpriseRadiusConfiguration) DeepCopyInto(out *WifiEnterpriseRadiusConfiguration) {
	*out = *in
	out.NasID = in.NasID
	out.RadiusProfileRef = in.RadiusProfileRef
	if in.MACAuthenticationConfiguration != nil {
		in, out := &in.MACAuthenticationConfiguration, &out.MACAuthenticationConfiguration
		*out = new(WifiRadiusMacAuthenticationConfiguration)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WifiEnterpriseRadiusConfiguration.
func (in *WifiEnterpriseRadiusConfiguration) DeepCopy() *WifiEnterpriseRadiusConfiguration {
	if in == nil {
		return nil
	}
	out := new(WifiEnterpriseRadiusConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WifiHandoffSuggestionsConfiguration) DeepCopyInto(out *WifiHandoffSuggestionsConfiguration) {
	*out = *in
	if in.Band5GHzRssiThreshold != nil {
		in, out := &in.Band5GHzRssiThreshold, &out.Band5GHzRssiThreshold
		*out = new(int32)
		**out = **in
	}
	if in.Band6GHzRssiThreshold != nil {
		in, out := &in.Band6GHzRssiThreshold, &out.Band6GHzRssiThreshold
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WifiHandoffSuggestionsConfiguration.
func (in *WifiHandoffSuggestionsConfiguration) DeepCopy() *WifiHandoffSuggestionsConfiguration {
	if in == nil {
		return nil
	}
	out := new(WifiHandoffSuggestionsConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WifiHotspotConfiguration) DeepCopyInto(out *WifiHotspotConfiguration) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WifiHotspotConfiguration.
func (in *WifiHotspotConfiguration) DeepCopy() *WifiHotspotConfiguration {
	if in == nil {
		return nil
	}
	out := new(WifiHotspotConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WifiMDNSCustomService) DeepCopyInto(out *WifiMDNSCustomService) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WifiMDNSCustomService.
func (in *WifiMDNSCustomService) DeepCopy() *WifiMDNSCustomService {
	if in == nil {
		return nil
	}
	out := new(WifiMDNSCustomService)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WifiMDNSPredefinedService) DeepCopyInto(out *WifiMDNSPredefinedService) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WifiMDNSPredefinedService.
func (in *WifiMDNSPredefinedService) DeepCopy() *WifiMDNSPredefinedService {
	if in == nil {
		return nil
	}
	out := new(WifiMDNSPredefinedService)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WifiMDNSProxyConfiguration) DeepCopyInto(out *WifiMDNSProxyConfiguration) {
	*out = *in
	if in.Policies != nil {
		in, out := &in.Policies, &out.Policies
		*out = make([]WifiMDNSProxyPolicy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WifiMDNSProxyConfiguration.
func (in *WifiMDNSProxyConfiguration) DeepCopy() *WifiMDNSProxyConfiguration {
	if in == nil {
		return nil
	}
	out := new(WifiMDNSProxyConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WifiMDNSProxyPolicy) DeepCopyInto(out *WifiMDNSProxyPolicy) {
	*out = *in
	if in.DeviceTags != nil {
		in, out := &in.DeviceTags, &out.DeviceTags
		*out = make([]DeviceTagSelector, len(*in))
		copy(*out, *in)
	}
	if in.BridgingNetworkRefs != nil {
		in, out := &in.BridgingNetworkRefs, &out.BridgingNetworkRefs
		*out = make([]CoreRef, len(*in))
		copy(*out, *in)
	}
	if in.ServiceFilter != nil {
		in, out := &in.ServiceFilter, &out.ServiceFilter
		*out = make([]WifiMDNSService, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WifiMDNSProxyPolicy.
func (in *WifiMDNSProxyPolicy) DeepCopy() *WifiMDNSProxyPolicy {
	if in == nil {
		return nil
	}
	out := new(WifiMDNSProxyPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WifiMDNSService) DeepCopyInto(out *WifiMDNSService) {
	*out = *in
	if in.Custom != nil {
		in, out := &in.Custom, &out.Custom
		*out = new(WifiMDNSCustomService)
		**out = **in
	}
	if in.Predefined != nil {
		in, out := &in.Predefined, &out.Predefined
		*out = new(WifiMDNSPredefinedService)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WifiMDNSService.
func (in *WifiMDNSService) DeepCopy() *WifiMDNSService {
	if in == nil {
		return nil
	}
	out := new(WifiMDNSService)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WifiMulticastFilteringPolicy) DeepCopyInto(out *WifiMulticastFilteringPolicy) {
	*out = *in
	if in.SourceMacAddressFilter != nil {
		in, out := &in.SourceMacAddressFilter, &out.SourceMacAddressFilter
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WifiMulticastFilteringPolicy.
func (in *WifiMulticastFilteringPolicy) DeepCopy() *WifiMulticastFilteringPolicy {
	if in == nil {
		return nil
	}
	out := new(WifiMulticastFilteringPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WifiNonEnterpriseRadiusConfiguration) DeepCopyInto(out *WifiNonEnterpriseRadiusConfiguration) {
	*out = *in
	out.MACAuthenticationConfiguration = in.MACAuthenticationConfiguration
	out.NasID = in.NasID
	out.RadiusProfileRef = in.RadiusProfileRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WifiNonEnterpriseRadiusConfiguration.
func (in *WifiNonEnterpriseRadiusConfiguration) DeepCopy() *WifiNonEnterpriseRadiusConfiguration {
	if in == nil {
		return nil
	}
	out := new(WifiNonEnterpriseRadiusConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WifiOpenSecurityConfiguration) DeepCopyInto(out *WifiOpenSecurityConfiguration) {
	*out = *in
	if in.Encryption != nil {
		in, out := &in.Encryption, &out.Encryption
		*out = new(string)
		**out = **in
	}
	if in.RadiusConfiguration != nil {
		in, out := &in.RadiusConfiguration, &out.RadiusConfiguration
		*out = new(WifiNonEnterpriseRadiusConfiguration)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WifiOpenSecurityConfiguration.
func (in *WifiOpenSecurityConfiguration) DeepCopy() *WifiOpenSecurityConfiguration {
	if in == nil {
		return nil
	}
	out := new(WifiOpenSecurityConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WifiPresharedKey) DeepCopyInto(out *WifiPresharedKey) {
	*out = *in
	out.Network = in.Network
	in.Passphrase.DeepCopyInto(&out.Passphrase)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WifiPresharedKey.
func (in *WifiPresharedKey) DeepCopy() *WifiPresharedKey {
	if in == nil {
		return nil
	}
	out := new(WifiPresharedKey)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WifiRadiusMacAuthenticationConfiguration) DeepCopyInto(out *WifiRadiusMacAuthenticationConfiguration) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WifiRadiusMacAuthenticationConfiguration.
func (in *WifiRadiusMacAuthenticationConfiguration) DeepCopy() *WifiRadiusMacAuthenticationConfiguration {
	if in == nil {
		return nil
	}
	out := new(WifiRadiusMacAuthenticationConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WifiRadiusNasID) DeepCopyInto(out *WifiRadiusNasID) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WifiRadiusNasID.
func (in *WifiRadiusNasID) DeepCopy() *WifiRadiusNasID {
	if in == nil {
		return nil
	}
	out := new(WifiRadiusNasID)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WifiSAEConfiguration) DeepCopyInto(out *WifiSAEConfiguration) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WifiSAEConfiguration.
func (in *WifiSAEConfiguration) DeepCopy() *WifiSAEConfiguration {
	if in == nil {
		return nil
	}
	out := new(WifiSAEConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WifiSecurityConfiguration) DeepCopyInto(out *WifiSecurityConfiguration) {
	*out = *in
	if in.Open != nil {
		in, out := &in.Open, &out.Open
		*out = new(WifiOpenSecurityConfiguration)
		(*in).DeepCopyInto(*out)
	}
	if in.WPA2Personal != nil {
		in, out := &in.WPA2Personal, &out.WPA2Personal
		*out = new(WifiWPA2PersonalSecurityConfiguration)
		(*in).DeepCopyInto(*out)
	}
	if in.WPA2WPA3Personal != nil {
		in, out := &in.WPA2WPA3Personal, &out.WPA2WPA3Personal
		*out = new(WifiWPA2WPA3PersonalSecurityConfiguration)
		(*in).DeepCopyInto(*out)
	}
	if in.WPA3Personal != nil {
		in, out := &in.WPA3Personal, &out.WPA3Personal
		*out = new(WifiWPA3PersonalSecurityConfiguration)
		(*in).DeepCopyInto(*out)
	}
	if in.WPA2Enterprise != nil {
		in, out := &in.WPA2Enterprise, &out.WPA2Enterprise
		*out = new(WifiWPA2EnterpriseSecurityConfiguration)
		(*in).DeepCopyInto(*out)
	}
	if in.WPA2WPA3Enterprise != nil {
		in, out := &in.WPA2WPA3Enterprise, &out.WPA2WPA3Enterprise
		*out = new(WifiWPA2WPA3EnterpriseSecurityConfiguration)
		(*in).DeepCopyInto(*out)
	}
	if in.WPA3Enterprise != nil {
		in, out := &in.WPA3Enterprise, &out.WPA3Enterprise
		*out = new(WifiWPA3EnterpriseSecurityConfiguration)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WifiSecurityConfiguration.
func (in *WifiSecurityConfiguration) DeepCopy() *WifiSecurityConfiguration {
	if in == nil {
		return nil
	}
	out := new(WifiSecurityConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WifiWPA2EnterpriseSecurityConfiguration) DeepCopyInto(out *WifiWPA2EnterpriseSecurityConfiguration) {
	*out = *in
	in.RadiusConfiguration.DeepCopyInto(&out.RadiusConfiguration)
	if in.PmfMode != nil {
		in, out := &in.PmfMode, &out.PmfMode
		*out = new(string)
		**out = **in
	}
	if in.FastRoamingEnabled != nil {
		in, out := &in.FastRoamingEnabled, &out.FastRoamingEnabled
		*out = new(bool)
		**out = **in
	}
	if in.GroupRekeyIntervalSeconds != nil {
		in, out := &in.GroupRekeyIntervalSeconds, &out.GroupRekeyIntervalSeconds
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WifiWPA2EnterpriseSecurityConfiguration.
func (in *WifiWPA2EnterpriseSecurityConfiguration) DeepCopy() *WifiWPA2EnterpriseSecurityConfiguration {
	if in == nil {
		return nil
	}
	out := new(WifiWPA2EnterpriseSecurityConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WifiWPA2PersonalSecurityConfiguration) DeepCopyInto(out *WifiWPA2PersonalSecurityConfiguration) {
	*out = *in
	if in.Passphrase != nil {
		in, out := &in.Passphrase, &out.Passphrase
		*out = new(v1.SecretKeySelector)
		(*in).DeepCopyInto(*out)
	}
	if in.PresharedKeys != nil {
		in, out := &in.PresharedKeys, &out.PresharedKeys
		*out = make([]WifiPresharedKey, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.PmfMode != nil {
		in, out := &in.PmfMode, &out.PmfMode
		*out = new(string)
		**out = **in
	}
	if in.FastRoamingEnabled != nil {
		in, out := &in.FastRoamingEnabled, &out.FastRoamingEnabled
		*out = new(bool)
		**out = **in
	}
	if in.GroupRekeyIntervalSeconds != nil {
		in, out := &in.GroupRekeyIntervalSeconds, &out.GroupRekeyIntervalSeconds
		*out = new(int32)
		**out = **in
	}
	if in.RadiusConfiguration != nil {
		in, out := &in.RadiusConfiguration, &out.RadiusConfiguration
		*out = new(WifiNonEnterpriseRadiusConfiguration)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WifiWPA2PersonalSecurityConfiguration.
func (in *WifiWPA2PersonalSecurityConfiguration) DeepCopy() *WifiWPA2PersonalSecurityConfiguration {
	if in == nil {
		return nil
	}
	out := new(WifiWPA2PersonalSecurityConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WifiWPA2WPA3EnterpriseSecurityConfiguration) DeepCopyInto(out *WifiWPA2WPA3EnterpriseSecurityConfiguration) {
	*out = *in
	in.RadiusConfiguration.DeepCopyInto(&out.RadiusConfiguration)
	if in.FastRoamingEnabled != nil {
		in, out := &in.FastRoamingEnabled, &out.FastRoamingEnabled
		*out = new(bool)
		**out = **in
	}
	if in.GroupRekeyIntervalSeconds != nil {
		in, out := &in.GroupRekeyIntervalSeconds, &out.GroupRekeyIntervalSeconds
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WifiWPA2WPA3EnterpriseSecurityConfiguration.
func (in *WifiWPA2WPA3EnterpriseSecurityConfiguration) DeepCopy() *WifiWPA2WPA3EnterpriseSecurityConfiguration {
	if in == nil {
		return nil
	}
	out := new(WifiWPA2WPA3EnterpriseSecurityConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WifiWPA2WPA3PersonalSecurityConfiguration) DeepCopyInto(out *WifiWPA2WPA3PersonalSecurityConfiguration) {
	*out = *in
	in.Passphrase.DeepCopyInto(&out.Passphrase)
	out.SaeConfiguration = in.SaeConfiguration
	if in.FastRoamingEnabled != nil {
		in, out := &in.FastRoamingEnabled, &out.FastRoamingEnabled
		*out = new(bool)
		**out = **in
	}
	if in.GroupRekeyIntervalSeconds != nil {
		in, out := &in.GroupRekeyIntervalSeconds, &out.GroupRekeyIntervalSeconds
		*out = new(int32)
		**out = **in
	}
	if in.RadiusConfiguration != nil {
		in, out := &in.RadiusConfiguration, &out.RadiusConfiguration
		*out = new(WifiNonEnterpriseRadiusConfiguration)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WifiWPA2WPA3PersonalSecurityConfiguration.
func (in *WifiWPA2WPA3PersonalSecurityConfiguration) DeepCopy() *WifiWPA2WPA3PersonalSecurityConfiguration {
	if in == nil {
		return nil
	}
	out := new(WifiWPA2WPA3PersonalSecurityConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WifiWPA3EnterpriseSecurityConfiguration) DeepCopyInto(out *WifiWPA3EnterpriseSecurityConfiguration) {
	*out = *in
	in.RadiusConfiguration.DeepCopyInto(&out.RadiusConfiguration)
	if in.FastRoamingEnabled != nil {
		in, out := &in.FastRoamingEnabled, &out.FastRoamingEnabled
		*out = new(bool)
		**out = **in
	}
	if in.GroupRekeyIntervalSeconds != nil {
		in, out := &in.GroupRekeyIntervalSeconds, &out.GroupRekeyIntervalSeconds
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WifiWPA3EnterpriseSecurityConfiguration.
func (in *WifiWPA3EnterpriseSecurityConfiguration) DeepCopy() *WifiWPA3EnterpriseSecurityConfiguration {
	if in == nil {
		return nil
	}
	out := new(WifiWPA3EnterpriseSecurityConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WifiWPA3PersonalSecurityConfiguration) DeepCopyInto(out *WifiWPA3PersonalSecurityConfiguration) {
	*out = *in
	in.Passphrase.DeepCopyInto(&out.Passphrase)
	out.SaeConfiguration = in.SaeConfiguration
	if in.FastRoamingEnabled != nil {
		in, out := &in.FastRoamingEnabled, &out.FastRoamingEnabled
		*out = new(bool)
		**out = **in
	}
	if in.GroupRekeyIntervalSeconds != nil {
		in, out := &in.GroupRekeyIntervalSeconds, &out.GroupRekeyIntervalSeconds
		*out = new(int32)
		**out = **in
	}
	if in.RadiusConfiguration != nil {
		in, out := &in.RadiusConfiguration, &out.RadiusConfiguration
		*out = new(WifiNonEnterpriseRadiusConfiguration)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WifiWPA3PersonalSecurityConfiguration.
func (in *WifiWPA3PersonalSecurityConfiguration) DeepCopy() *WifiWPA3PersonalSecurityConfiguration {
	if in == nil {
		return nil
	}
	out := new(WifiWPA3PersonalSecurityConfiguration)
	in.DeepCopyInto(out)
	return out
}
