//go:build !ignore_autogenerated

/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CoreRef) DeepCopyInto(out *CoreRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CoreRef.
func (in *CoreRef) DeepCopy() *CoreRef {
	if in == nil {
		return nil
	}
	out := new(CoreRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DHCPGuarding) DeepCopyInto(out *DHCPGuarding) {
	*out = *in
	if in.TrustedDHCPServerIPAddresses != nil {
		in, out := &in.TrustedDHCPServerIPAddresses, &out.TrustedDHCPServerIPAddresses
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DHCPGuarding.
func (in *DHCPGuarding) DeepCopy() *DHCPGuarding {
	if in == nil {
		return nil
	}
	out := new(DHCPGuarding)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GatewayManagedIPv4Configuration) DeepCopyInto(out *GatewayManagedIPv4Configuration) {
	*out = *in
	if in.AdditionalHostIPSubnets != nil {
		in, out := &in.AdditionalHostIPSubnets, &out.AdditionalHostIPSubnets
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GatewayManagedIPv4Configuration.
func (in *GatewayManagedIPv4Configuration) DeepCopy() *GatewayManagedIPv4Configuration {
	if in == nil {
		return nil
	}
	out := new(GatewayManagedIPv4Configuration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GatewayNetworkOptions) DeepCopyInto(out *GatewayNetworkOptions) {
	*out = *in
	in.IPv4Configuration.DeepCopyInto(&out.IPv4Configuration)
	if in.IPv6Configuration != nil {
		in, out := &in.IPv6Configuration, &out.IPv6Configuration
		*out = new(IPv6Configuration)
		(*in).DeepCopyInto(*out)
	}
	if in.MDNSForwardingEnabled != nil {
		in, out := &in.MDNSForwardingEnabled, &out.MDNSForwardingEnabled
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GatewayNetworkOptions.
func (in *GatewayNetworkOptions) DeepCopy() *GatewayNetworkOptions {
	if in == nil {
		return nil
	}
	out := new(GatewayNetworkOptions)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IPv6ClientAddressAssignment) DeepCopyInto(out *IPv6ClientAddressAssignment) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IPv6ClientAddressAssignment.
func (in *IPv6ClientAddressAssignment) DeepCopy() *IPv6ClientAddressAssignment {
	if in == nil {
		return nil
	}
	out := new(IPv6ClientAddressAssignment)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IPv6Configuration) DeepCopyInto(out *IPv6Configuration) {
	*out = *in
	out.ClientAddressAssignment = in.ClientAddressAssignment
	if in.AdditionalHostIPSubnets != nil {
		in, out := &in.AdditionalHostIPSubnets, &out.AdditionalHostIPSubnets
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.DNSServerIPAddressesOverride != nil {
		in, out := &in.DNSServerIPAddressesOverride, &out.DNSServerIPAddressesOverride
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.RouterAdvertisement != nil {
		in, out := &in.RouterAdvertisement, &out.RouterAdvertisement
		*out = new(RouterAdvertisement)
		**out = **in
	}
	if in.PrefixDelegationWAN != nil {
		in, out := &in.PrefixDelegationWAN, &out.PrefixDelegationWAN
		*out = new(WANSelector)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IPv6Configuration.
func (in *IPv6Configuration) DeepCopy() *IPv6Configuration {
	if in == nil {
		return nil
	}
	out := new(IPv6Configuration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RouterAdvertisement) DeepCopyInto(out *RouterAdvertisement) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RouterAdvertisement.
func (in *RouterAdvertisement) DeepCopy() *RouterAdvertisement {
	if in == nil {
		return nil
	}
	out := new(RouterAdvertisement)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SwitchManagedIPv4Configuration) DeepCopyInto(out *SwitchManagedIPv4Configuration) {
	*out = *in
	if in.AdditionalHostIPSubnets != nil {
		in, out := &in.AdditionalHostIPSubnets, &out.AdditionalHostIPSubnets
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SwitchManagedIPv4Configuration.
func (in *SwitchManagedIPv4Configuration) DeepCopy() *SwitchManagedIPv4Configuration {
	if in == nil {
		return nil
	}
	out := new(SwitchManagedIPv4Configuration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SwitchNetworkOptions) DeepCopyInto(out *SwitchNetworkOptions) {
	*out = *in
	in.IPv4Configuration.DeepCopyInto(&out.IPv4Configuration)
	out.DeviceTagRef = in.DeviceTagRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SwitchNetworkOptions.
func (in *SwitchNetworkOptions) DeepCopy() *SwitchNetworkOptions {
	if in == nil {
		return nil
	}
	out := new(SwitchNetworkOptions)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UnifiController) DeepCopyInto(out *UnifiController) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UnifiController.
func (in *UnifiController) DeepCopy() *UnifiController {
	if in == nil {
		return nil
	}
	out := new(UnifiController)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *UnifiController) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UnifiControllerList) DeepCopyInto(out *UnifiControllerList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]UnifiController, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UnifiControllerList.
func (in *UnifiControllerList) DeepCopy() *UnifiControllerList {
	if in == nil {
		return nil
	}
	out := new(UnifiControllerList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *UnifiControllerList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UnifiControllerSpec) DeepCopyInto(out *UnifiControllerSpec) {
	*out = *in
	if in.SecretRef != nil {
		in, out := &in.SecretRef, &out.SecretRef
		*out = new(v1.SecretKeySelector)
		(*in).DeepCopyInto(*out)
	}
	if in.InsecureSkipVerify != nil {
		in, out := &in.InsecureSkipVerify, &out.InsecureSkipVerify
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UnifiControllerSpec.
func (in *UnifiControllerSpec) DeepCopy() *UnifiControllerSpec {
	if in == nil {
		return nil
	}
	out := new(UnifiControllerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UnifiControllerStatus) DeepCopyInto(out *UnifiControllerStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UnifiControllerStatus.
func (in *UnifiControllerStatus) DeepCopy() *UnifiControllerStatus {
	if in == nil {
		return nil
	}
	out := new(UnifiControllerStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UnifiNetwork) DeepCopyInto(out *UnifiNetwork) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UnifiNetwork.
func (in *UnifiNetwork) DeepCopy() *UnifiNetwork {
	if in == nil {
		return nil
	}
	out := new(UnifiNetwork)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *UnifiNetwork) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UnifiNetworkList) DeepCopyInto(out *UnifiNetworkList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]UnifiNetwork, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UnifiNetworkList.
func (in *UnifiNetworkList) DeepCopy() *UnifiNetworkList {
	if in == nil {
		return nil
	}
	out := new(UnifiNetworkList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *UnifiNetworkList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UnifiNetworkSpec) DeepCopyInto(out *UnifiNetworkSpec) {
	*out = *in
	out.SiteRef = in.SiteRef
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.DHCPGuarding != nil {
		in, out := &in.DHCPGuarding, &out.DHCPGuarding
		*out = new(DHCPGuarding)
		(*in).DeepCopyInto(*out)
	}
	if in.Gateway != nil {
		in, out := &in.Gateway, &out.Gateway
		*out = new(GatewayNetworkOptions)
		(*in).DeepCopyInto(*out)
	}
	if in.Switch != nil {
		in, out := &in.Switch, &out.Switch
		*out = new(SwitchNetworkOptions)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UnifiNetworkSpec.
func (in *UnifiNetworkSpec) DeepCopy() *UnifiNetworkSpec {
	if in == nil {
		return nil
	}
	out := new(UnifiNetworkSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UnifiNetworkStatus) DeepCopyInto(out *UnifiNetworkStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UnifiNetworkStatus.
func (in *UnifiNetworkStatus) DeepCopy() *UnifiNetworkStatus {
	if in == nil {
		return nil
	}
	out := new(UnifiNetworkStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UnifiSite) DeepCopyInto(out *UnifiSite) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UnifiSite.
func (in *UnifiSite) DeepCopy() *UnifiSite {
	if in == nil {
		return nil
	}
	out := new(UnifiSite)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *UnifiSite) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UnifiSiteList) DeepCopyInto(out *UnifiSiteList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]UnifiSite, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UnifiSiteList.
func (in *UnifiSiteList) DeepCopy() *UnifiSiteList {
	if in == nil {
		return nil
	}
	out := new(UnifiSiteList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *UnifiSiteList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UnifiSiteSpec) DeepCopyInto(out *UnifiSiteSpec) {
	*out = *in
	out.ControllerRef = in.ControllerRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UnifiSiteSpec.
func (in *UnifiSiteSpec) DeepCopy() *UnifiSiteSpec {
	if in == nil {
		return nil
	}
	out := new(UnifiSiteSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UnifiSiteStatus) DeepCopyInto(out *UnifiSiteStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UnifiSiteStatus.
func (in *UnifiSiteStatus) DeepCopy() *UnifiSiteStatus {
	if in == nil {
		return nil
	}
	out := new(UnifiSiteStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WANSelector) DeepCopyInto(out *WANSelector) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WANSelector.
func (in *WANSelector) DeepCopy() *WANSelector {
	if in == nil {
		return nil
	}
	out := new(WANSelector)
	in.DeepCopyInto(out)
	return out
}
