{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "unifi-operator.fullname" . }}-manager-role
  labels:
    {{- include "unifi-operator.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
- apiGroups:
  - unifi.supporterino.de
  resources:
  - unificontrollers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - unifi.supporterino.de
  resources:
  - unificontrollers/status
  - unififirewallzones/status
  - unifinetworks/status
  - unifisites/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - unifi.supporterino.de
  resources:
  - unififirewallzones
  - unifinetworks
  verbs:
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - unifi.supporterino.de
  resources:
  - unifisites
  verbs:
  - get
  - list
  - patch
  - update
  - watch
{{- end }}
