{{- if .Values.rbac.create }}
# This rule is not used by the operator itself. It grants create/update/delete
# over unifi.supporterino.de without the ability to manage RBAC.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "unifi-operator.fullname" . }}-unificontroller-editor-role
  labels:
    {{- include "unifi-operator.labels" . | nindent 4 }}
rules:
- apiGroups:
  - unifi.supporterino.de
  resources:
  - unificontrollers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - unifi.supporterino.de
  resources:
  - unificontrollers/status
  verbs:
  - get
{{- end }}
