{{- if .Values.rbac.create }}
# This rule is not used by the operator itself. It is provided to allow a
# cluster admin to delegate full permissions over unifi.supporterino.de.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "unifi-operator.fullname" . }}-unificontroller-admin-role
  labels:
    {{- include "unifi-operator.labels" . | nindent 4 }}
rules:
- apiGroups:
  - unifi.supporterino.de
  resources:
  - unificontrollers
  verbs:
  - '*'
- apiGroups:
  - unifi.supporterino.de
  resources:
  - unificontrollers/status
  verbs:
  - get
{{- end }}
