apiVersion: unifi.supporterino.de/v1alpha1
kind: UnifiNetwork
metadata:
  labels:
    app.kubernetes.io/name: operator
    app.kubernetes.io/managed-by: kustomize
  name: unifinetwork-sample
spec:
  siteRef:
    name: unifisite-sample
  management: GATEWAY
  name: lan
  enabled: true
  vlanId: 10
  gateway:
    cellularBackupEnabled: false
    internetAccessEnabled: true
    isolationEnabled: false
    ipv4Configuration:
      autoScaleEnabled: false
      hostIpAddress: 10.0.0.1
      prefixLength: 24
